{% set name = "sshtunnel" %}
{% set version = "0.1.3" %}
{% set sha256 = "598805bb106d8b6d8033a04f2a6b4a64fc9d08a937fe994c7700d0c32d617050" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.zip
  url: https://github.com/pahaz/sshtunnel/archive/{{ version }}.zip
  sha256: {{ sha256 }}

build:
  entry_points:
    - sshtunnel = sshtunnel:_cli_main
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt


requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - paramiko

test:
  imports:
    - sshtunnel

about:
  home: http://github.com/pahaz/sshtunnel
  license: MIT
  license_file: LICENSE
  summary: 'Pure Python SSH tunnels'
  dev_url: https://github.com/pahaz/sshtunnel

extra:
  recipe-maintainers:
    - basnijholt
    - pahaz
    - fernandezcuesta
