{% set name = "sshtunnel" %}
{% set version = "0.1.1" %}
{% set sha256 = "6256a368a0ff1177ee23e9d03fe1bfacea0ae00d1bec6652a063f05132643bea" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.zip
  url: https://github.com/pahaz/sshtunnel/archive/{{ version }}.zip
  sha256: {{ sha256 }}

build:
  entry_points:
    - sshtunnel = sshtunnel:_cli_main
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt


requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - paramiko

test:
  imports:
    - sshtunnel

about:
  home: http://github.com/pahaz/sshtunnel
  license: MIT
  license_file: LICENSE
  summary: 'Pure Python SSH tunnels'
  dev_url: https://github.com/pahaz/sshtunnel

extra:
  recipe-maintainers:
    - basnijholt
