travis:
  secure:
    BINSTAR_TOKEN: SAsfF8YC4adU3Tgifws9zlW1eKTME7g0dloh/9yh/dh68SRJLt9wTlwCkqn3jedThjYoMN3oBySWycqSSHHN22n/wWDou1F0Yx48hrKiQc0BttkIQJ5ouYJ7iOMaC/eIJGtzot/NQTkjTxIgSzrK+yvIaqi+J1+GGsqGhOvDKZKVL8o6t3LhLDoZEAIptzMXy9EaNecLgwBmwUmNuMTTfwKFo2Cg1E/cIHqxonImUleoz0uUdq2E8tuIkVMKQgPDIZ8OesyHRVR/FDYvYPZoRIeq4Thv+HwHqouUsLestiQteKSiLzNQ3jJeViCAYJY5F8cZnmHzSLpJj9/y1cPosfRzX2ni7OVn8uOuXHUsRIT5bHEGLu3y0UcVd4C/f/yFirVxwYraQJK3Tz4yS2locHYP7xTh7YHqnUHsfJu5Aos2gRDQSo0jA72f42C6ta5w/A4O6QkJw7Pqzw6qgeykEn5eY+GaKsjtzXG1QvQM7kTXgqN+d+U8Mxy3BHsttnW5VHwbCqAQR7v6+frP0X6LjMKsyLt/4FfPdofUr3F/ICTG1msQTJZYK4uPvi9GYI4y9OFPcgLsX/4khrIR252WEppEGW+W5n+gmYDoxtl9hBfW9rox5Euh7CFsKoLgHfq6iPwjTttYhQR7X1a0AmadwrRPTs0oICjcjzdTY5wdgJA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
