travis:
  secure:
    BINSTAR_TOKEN: UiEcqrVu9r6LXqIWZJ/MCUsBo+oAizhnLrcjk0kwu7Ar59STZi2MABWurdF7EKDAyL5oRKOqyoQeRKCFcqtrIgCYS6oGLe6glO9yLGpbQ+KofxoaQZZWrOHdz/BjPu9Gv3Uxfj7w6EsCroZBdIBjUO7HntG4MnVidW0bj52TipgxeAEFPJIjfVk9mEZyxJ238nYlDv9p1i1YXxEB5UzmlsEHBcowanSPQMBMhBacgbvkAOw5SJJmfy2odDEeukzMf0PRBLnWILHt/YYqvo8l4W6Qmm6qsnyCgsC5RYsqJQ4+U1gLFYPUVbMXczlNo/pHk2dkLsT8z3eQLkpFbnybGqlBLyBIagak0V48LvOA+NFC+T8FakQHK89mowCOQj7DDYEDVyzjDe2jUzBJBxVjxXAnSf5T3mh/EUQnev0JUyu8F2JRyDMuMsogBOOyKGZAr/8F364om8Cy+kVZnG9+pFZJKa7hirpnwxKts0ZH+SfgDE/ByHXWaWug7RghPmxwk3vLiO7Ad6z7KCQmm8eESy6zy4POIZ5cB8RPP9QF60JYPGEyU+qZM0JRLYOhrcEpBKOu7+jIxWGXDI9wYJvktXDBP1tmz2jgC5Kvbm/+ajARLsoL2aCju5gTyB7Ove1xLceHifdXPRaR4Hgo/vLT43xdEkTP9W3GBtHfxD4w6JM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
