travis:
  secure:
    BINSTAR_TOKEN: XZ61slcceylILF8Zn3GfoN1fCF8fitvEe263O8/3/b/SSMB5xRPS3vTtYHzYjj0HVG/ggDSjxN19Q8jf13J67TGS5h66TH+yi4cGtIbOvihxc0ZS/R7eGgSQBjZYZ9/f7YwyCaDuxyo/mNNDR0dF5RypJl1UXP5ujlPo+bIJ3Nb0VsddpIOA1YanM+03wo66C1VmKl5C1SKPWBkUwHwTVYZu7sM8l6QdXzGjKsvv1hNprE6ZvSEwLwSM2ayEptJfKoIxw3KmUCrDeaYaNRO9fZbMVHNqWUeyvsh4cyu0ll94mK+vRi6MVZu0XdBJ41V3qxeAAyjjz3Y/F2T8/SBkaULIbo21W15aLmPitQ7ZxBiilbLmbA7kuZsCSnkHIBGU1W/maxV2mDcdku56ZTjDyqSsRnlsqeiOiPMkez5BST1grhkR5G1C3rGjgOlMoK0/ZGLkP/mFIU5wp0PWn7a4JJGsqTIB0vF9K003TkS/cN/TtoaI8pUiTFLeHBv8RmBT6eCOT9mw2zBfNsMfhqgnn30Er9K2MdGuRtKilTW1N1CuchwZnXvhsQadiDhfsh82x9HHODX7SeHAP3JL6OIOWIO1Kc12yfsI53EY3OLyFUAYB3okWIJULnVQ7yEGZvRHjb+yuoOC62nxLvv13f6soMwjXTehjgUs/9Es7QHYGSY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
